[global]
developmentMode = false

[server]
enableCORS = false
enableXsrfProtection = false
address = "0.0.0.0"
port = 8501
maxUploadSize = 200
embedded=true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501

[theme]
base = "light"
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = false
caching = true
displayEnabled = true

[runner]
magicEnabled = false
fastReruns = true
maxCachedIterations = 100

[logger]
level = "critical"

[mapbox]
token = ""
